version: '3.8'

services:
  basic_versioning:
    build: ./basic_versioning
    ports:
      - "5001:5001"
    env_file:
      - .env

  sensor_api:
    build: ./sensor_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - basic_versioning
