version: '3.8'

services:
  basic_versioning:
    build: ./basic_versioning
    ports:
      - "5001:5001"
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/version"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s

  sensor_api:
    build: ./sensor_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
      basic_versioning:
        condition: service_started
    networks:
      - app-network
    environment:
      - VERSION_BASE_URL=http://basic_versioning:5001
      - TEMPERATURE_BASE_URL=http://sensor_api:5000
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  app-network:
    driver: bridge

volumes:
  minio_data:
  minio_config:
