apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hivebox-sensor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Correct path rewrites
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Enforce HTTPS
    nginx.ingress.kubernetes.io/hsts: "true"  # Enable HTTP Strict Transport Security
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"  # 1 year HSTS duration
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    kubernetes.io/tls-acme: "true"  # Auto-generate certificates with cert-manager

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hivebox.local
      secretName: tls-secret  # Ensure tls-secret is created properly
  rules:
    - host: hivebox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-sensor-service
                port:
                  number: 80
