
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hivebox-sensor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  
    
spec:
  ingressClassName: nginx
  rules:
    - host: hivebox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-sensor-service
                port:
                  number: 80
