apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hivebox-sensor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  
    kubernetes.io/tls-acme: "true"                    
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hivebox.local
      secretName: tls-secret  
  rules:
    - host: hivebox.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hivebox-sensor-service
                port:
                  number: 80
